#!/usr/bin/env python3
import sys
import rclpy
from turtlebot3_gazebo.nodes.global_planner_node import main

def main_rrt():
    # Override default planner_type to rrtstar via remapping or param
    sys.argv += ['--ros-args', '-p', 'planner_type:=rrtstar']
    main()

main_rrt()
